export interface CountryEntry {
  id: string;
  name: string;
  aliases: string[];
}

// Roughly all UN member states, keyed by the slug used for public/borders/<id>.svg
// (only countries actually referenced by a puzzle need a matching SVG — this
// list is the full autocomplete/answer-normalization surface).
export const COUNTRIES: CountryEntry[] = [
  { id: 'afghanistan', name: 'Afghanistan', aliases: [] },
  { id: 'albania', name: 'Albania', aliases: [] },
  { id: 'algeria', name: 'Algeria', aliases: [] },
  { id: 'andorra', name: 'Andorra', aliases: [] },
  { id: 'angola', name: 'Angola', aliases: [] },
  { id: 'antigua-and-barbuda', name: 'Antigua and Barbuda', aliases: [] },
  { id: 'argentina', name: 'Argentina', aliases: [] },
  { id: 'armenia', name: 'Armenia', aliases: [] },
  { id: 'australia', name: 'Australia', aliases: [] },
  { id: 'austria', name: 'Austria', aliases: [] },
  { id: 'azerbaijan', name: 'Azerbaijan', aliases: [] },
  { id: 'bahamas', name: 'Bahamas', aliases: ['the bahamas'] },
  { id: 'bahrain', name: 'Bahrain', aliases: [] },
  { id: 'bangladesh', name: 'Bangladesh', aliases: [] },
  { id: 'barbados', name: 'Barbados', aliases: [] },
  { id: 'belarus', name: 'Belarus', aliases: [] },
  { id: 'belgium', name: 'Belgium', aliases: [] },
  { id: 'belize', name: 'Belize', aliases: [] },
  { id: 'benin', name: 'Benin', aliases: [] },
  { id: 'bhutan', name: 'Bhutan', aliases: [] },
  { id: 'bolivia', name: 'Bolivia', aliases: [] },
  { id: 'bosnia-and-herzegovina', name: 'Bosnia and Herzegovina', aliases: ['bosnia'] },
  { id: 'botswana', name: 'Botswana', aliases: [] },
  { id: 'brazil', name: 'Brazil', aliases: [] },
  { id: 'brunei', name: 'Brunei', aliases: [] },
  { id: 'bulgaria', name: 'Bulgaria', aliases: [] },
  { id: 'burkina-faso', name: 'Burkina Faso', aliases: [] },
  { id: 'burundi', name: 'Burundi', aliases: [] },
  { id: 'cambodia', name: 'Cambodia', aliases: [] },
  { id: 'cameroon', name: 'Cameroon', aliases: [] },
  { id: 'canada', name: 'Canada', aliases: [] },
  { id: 'cape-verde', name: 'Cape Verde', aliases: ['cabo verde'] },
  { id: 'central-african-republic', name: 'Central African Republic', aliases: [] },
  { id: 'chad', name: 'Chad', aliases: [] },
  { id: 'chile', name: 'Chile', aliases: [] },
  { id: 'china', name: 'China', aliases: ["people's republic of china", 'prc'] },
  { id: 'colombia', name: 'Colombia', aliases: [] },
  { id: 'comoros', name: 'Comoros', aliases: [] },
  { id: 'costa-rica', name: 'Costa Rica', aliases: [] },
  { id: 'croatia', name: 'Croatia', aliases: [] },
  { id: 'cuba', name: 'Cuba', aliases: [] },
  { id: 'cyprus', name: 'Cyprus', aliases: [] },
  { id: 'czechia', name: 'Czechia', aliases: ['czech republic'] },
  { id: 'dr-congo', name: 'Democratic Republic of the Congo', aliases: ['dr congo', 'drc', 'congo-kinshasa'] },
  { id: 'denmark', name: 'Denmark', aliases: [] },
  { id: 'djibouti', name: 'Djibouti', aliases: [] },
  { id: 'dominica', name: 'Dominica', aliases: [] },
  { id: 'dominican-republic', name: 'Dominican Republic', aliases: [] },
  { id: 'ecuador', name: 'Ecuador', aliases: [] },
  { id: 'egypt', name: 'Egypt', aliases: [] },
  { id: 'el-salvador', name: 'El Salvador', aliases: [] },
  { id: 'equatorial-guinea', name: 'Equatorial Guinea', aliases: [] },
  { id: 'eritrea', name: 'Eritrea', aliases: [] },
  { id: 'estonia', name: 'Estonia', aliases: [] },
  { id: 'eswatini', name: 'Eswatini', aliases: ['swaziland'] },
  { id: 'ethiopia', name: 'Ethiopia', aliases: [] },
  { id: 'fiji', name: 'Fiji', aliases: [] },
  { id: 'finland', name: 'Finland', aliases: [] },
  { id: 'france', name: 'France', aliases: [] },
  { id: 'gabon', name: 'Gabon', aliases: [] },
  { id: 'gambia', name: 'Gambia', aliases: ['the gambia'] },
  { id: 'georgia', name: 'Georgia', aliases: [] },
  { id: 'germany', name: 'Germany', aliases: [] },
  { id: 'ghana', name: 'Ghana', aliases: [] },
  { id: 'greece', name: 'Greece', aliases: [] },
  { id: 'grenada', name: 'Grenada', aliases: [] },
  { id: 'guatemala', name: 'Guatemala', aliases: [] },
  { id: 'guinea', name: 'Guinea', aliases: [] },
  { id: 'guinea-bissau', name: 'Guinea-Bissau', aliases: [] },
  { id: 'guyana', name: 'Guyana', aliases: [] },
  { id: 'haiti', name: 'Haiti', aliases: [] },
  { id: 'honduras', name: 'Honduras', aliases: [] },
  { id: 'hungary', name: 'Hungary', aliases: [] },
  { id: 'iceland', name: 'Iceland', aliases: [] },
  { id: 'india', name: 'India', aliases: [] },
  { id: 'indonesia', name: 'Indonesia', aliases: [] },
  { id: 'iran', name: 'Iran', aliases: [] },
  { id: 'iraq', name: 'Iraq', aliases: [] },
  { id: 'ireland', name: 'Ireland', aliases: [] },
  { id: 'israel', name: 'Israel', aliases: [] },
  { id: 'italy', name: 'Italy', aliases: [] },
  { id: 'ivory-coast', name: 'Ivory Coast', aliases: ["cote d'ivoire", 'côte d’ivoire', 'cote divoire'] },
  { id: 'jamaica', name: 'Jamaica', aliases: [] },
  { id: 'japan', name: 'Japan', aliases: [] },
  { id: 'jordan', name: 'Jordan', aliases: [] },
  { id: 'kazakhstan', name: 'Kazakhstan', aliases: [] },
  { id: 'kenya', name: 'Kenya', aliases: [] },
  { id: 'kiribati', name: 'Kiribati', aliases: [] },
  { id: 'kosovo', name: 'Kosovo', aliases: [] },
  { id: 'kuwait', name: 'Kuwait', aliases: [] },
  { id: 'kyrgyzstan', name: 'Kyrgyzstan', aliases: [] },
  { id: 'laos', name: 'Laos', aliases: [] },
  { id: 'latvia', name: 'Latvia', aliases: [] },
  { id: 'lebanon', name: 'Lebanon', aliases: [] },
  { id: 'lesotho', name: 'Lesotho', aliases: [] },
  { id: 'liberia', name: 'Liberia', aliases: [] },
  { id: 'libya', name: 'Libya', aliases: [] },
  { id: 'liechtenstein', name: 'Liechtenstein', aliases: [] },
  { id: 'lithuania', name: 'Lithuania', aliases: [] },
  { id: 'luxembourg', name: 'Luxembourg', aliases: [] },
  { id: 'madagascar', name: 'Madagascar', aliases: [] },
  { id: 'malawi', name: 'Malawi', aliases: [] },
  { id: 'malaysia', name: 'Malaysia', aliases: [] },
  { id: 'maldives', name: 'Maldives', aliases: [] },
  { id: 'mali', name: 'Mali', aliases: [] },
  { id: 'malta', name: 'Malta', aliases: [] },
  { id: 'marshall-islands', name: 'Marshall Islands', aliases: [] },
  { id: 'mauritania', name: 'Mauritania', aliases: [] },
  { id: 'mauritius', name: 'Mauritius', aliases: [] },
  { id: 'mexico', name: 'Mexico', aliases: [] },
  { id: 'micronesia', name: 'Micronesia', aliases: [] },
  { id: 'moldova', name: 'Moldova', aliases: [] },
  { id: 'monaco', name: 'Monaco', aliases: [] },
  { id: 'mongolia', name: 'Mongolia', aliases: [] },
  { id: 'montenegro', name: 'Montenegro', aliases: [] },
  { id: 'morocco', name: 'Morocco', aliases: [] },
  { id: 'mozambique', name: 'Mozambique', aliases: [] },
  { id: 'myanmar', name: 'Myanmar', aliases: ['burma'] },
  { id: 'namibia', name: 'Namibia', aliases: [] },
  { id: 'nauru', name: 'Nauru', aliases: [] },
  { id: 'nepal', name: 'Nepal', aliases: [] },
  { id: 'netherlands', name: 'Netherlands', aliases: ['holland', 'the netherlands'] },
  { id: 'new-zealand', name: 'New Zealand', aliases: [] },
  { id: 'nicaragua', name: 'Nicaragua', aliases: [] },
  { id: 'niger', name: 'Niger', aliases: [] },
  { id: 'nigeria', name: 'Nigeria', aliases: [] },
  { id: 'north-korea', name: 'North Korea', aliases: ["democratic people's republic of korea", 'dprk'] },
  { id: 'north-macedonia', name: 'North Macedonia', aliases: ['macedonia'] },
  { id: 'norway', name: 'Norway', aliases: [] },
  { id: 'oman', name: 'Oman', aliases: [] },
  { id: 'pakistan', name: 'Pakistan', aliases: [] },
  { id: 'palau', name: 'Palau', aliases: [] },
  { id: 'panama', name: 'Panama', aliases: [] },
  { id: 'papua-new-guinea', name: 'Papua New Guinea', aliases: [] },
  { id: 'paraguay', name: 'Paraguay', aliases: [] },
  { id: 'peru', name: 'Peru', aliases: [] },
  { id: 'philippines', name: 'Philippines', aliases: ['the philippines'] },
  { id: 'poland', name: 'Poland', aliases: [] },
  { id: 'portugal', name: 'Portugal', aliases: [] },
  { id: 'qatar', name: 'Qatar', aliases: [] },
  { id: 'congo', name: 'Republic of the Congo', aliases: ['congo-brazzaville'] },
  { id: 'romania', name: 'Romania', aliases: [] },
  { id: 'russia', name: 'Russia', aliases: ['russian federation'] },
  { id: 'rwanda', name: 'Rwanda', aliases: [] },
  { id: 'saint-kitts-and-nevis', name: 'Saint Kitts and Nevis', aliases: [] },
  { id: 'saint-lucia', name: 'Saint Lucia', aliases: [] },
  { id: 'saint-vincent', name: 'Saint Vincent and the Grenadines', aliases: [] },
  { id: 'samoa', name: 'Samoa', aliases: [] },
  { id: 'san-marino', name: 'San Marino', aliases: [] },
  { id: 'sao-tome-and-principe', name: 'Sao Tome and Principe', aliases: [] },
  { id: 'saudi-arabia', name: 'Saudi Arabia', aliases: [] },
  { id: 'senegal', name: 'Senegal', aliases: [] },
  { id: 'serbia', name: 'Serbia', aliases: [] },
  { id: 'seychelles', name: 'Seychelles', aliases: [] },
  { id: 'sierra-leone', name: 'Sierra Leone', aliases: [] },
  { id: 'singapore', name: 'Singapore', aliases: [] },
  { id: 'slovakia', name: 'Slovakia', aliases: [] },
  { id: 'slovenia', name: 'Slovenia', aliases: [] },
  { id: 'solomon-islands', name: 'Solomon Islands', aliases: [] },
  { id: 'somalia', name: 'Somalia', aliases: [] },
  { id: 'south-africa', name: 'South Africa', aliases: [] },
  { id: 'south-korea', name: 'South Korea', aliases: ['korea', 'republic of korea'] },
  { id: 'south-sudan', name: 'South Sudan', aliases: [] },
  { id: 'spain', name: 'Spain', aliases: [] },
  { id: 'sri-lanka', name: 'Sri Lanka', aliases: [] },
  { id: 'sudan', name: 'Sudan', aliases: [] },
  { id: 'suriname', name: 'Suriname', aliases: [] },
  { id: 'sweden', name: 'Sweden', aliases: [] },
  { id: 'switzerland', name: 'Switzerland', aliases: [] },
  { id: 'syria', name: 'Syria', aliases: [] },
  { id: 'taiwan', name: 'Taiwan', aliases: [] },
  { id: 'tajikistan', name: 'Tajikistan', aliases: [] },
  { id: 'tanzania', name: 'Tanzania', aliases: [] },
  { id: 'thailand', name: 'Thailand', aliases: [] },
  { id: 'timor-leste', name: 'Timor-Leste', aliases: ['east timor'] },
  { id: 'togo', name: 'Togo', aliases: [] },
  { id: 'tonga', name: 'Tonga', aliases: [] },
  { id: 'trinidad-and-tobago', name: 'Trinidad and Tobago', aliases: [] },
  { id: 'tunisia', name: 'Tunisia', aliases: [] },
  { id: 'turkey', name: 'Turkey', aliases: ['turkiye', 'türkiye'] },
  { id: 'turkmenistan', name: 'Turkmenistan', aliases: [] },
  { id: 'tuvalu', name: 'Tuvalu', aliases: [] },
  { id: 'uganda', name: 'Uganda', aliases: [] },
  { id: 'ukraine', name: 'Ukraine', aliases: [] },
  { id: 'united-arab-emirates', name: 'United Arab Emirates', aliases: ['uae', 'emirates'] },
  { id: 'united-kingdom', name: 'United Kingdom', aliases: ['uk', 'britain', 'great britain', 'england'] },
  { id: 'united-states', name: 'United States', aliases: ['usa', 'us', 'united states of america', 'america'] },
  { id: 'uruguay', name: 'Uruguay', aliases: [] },
  { id: 'uzbekistan', name: 'Uzbekistan', aliases: [] },
  { id: 'vanuatu', name: 'Vanuatu', aliases: [] },
  { id: 'vatican-city', name: 'Vatican City', aliases: ['the vatican', 'holy see'] },
  { id: 'venezuela', name: 'Venezuela', aliases: [] },
  { id: 'vietnam', name: 'Vietnam', aliases: [] },
  { id: 'yemen', name: 'Yemen', aliases: [] },
  { id: 'zambia', name: 'Zambia', aliases: [] },
  { id: 'zimbabwe', name: 'Zimbabwe', aliases: [] },
];

export function normalizeCountryQuery(s: string): string {
  return s
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .trim()
    .replace(/^the\s+/, '')
    .replace(/[^a-z0-9\s]/g, '');
}

export function searchCountries(query: string, limit = 8): CountryEntry[] {
  const q = normalizeCountryQuery(query);
  if (!q) return [];
  const matches = COUNTRIES.filter((c) => {
    const candidates = [c.name, ...c.aliases].map(normalizeCountryQuery);
    return candidates.some((cand) => cand.includes(q));
  });
  // Prefix matches first, then substring matches.
  matches.sort((a, b) => {
    const aPrefix = normalizeCountryQuery(a.name).startsWith(q) ? 0 : 1;
    const bPrefix = normalizeCountryQuery(b.name).startsWith(q) ? 0 : 1;
    return aPrefix - bPrefix || a.name.localeCompare(b.name);
  });
  return matches.slice(0, limit);
}
